/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-12-22 03:49:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/Project_sell/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/glassProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1605970948952L));
    _jspx_dependants.put("jar:file:/D:/Project_sell/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/glassProject/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603912215637L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1603909552989L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>");
      if (_jspx_meth_dec_005ftitle_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" </section> <!-- end s-pageheader -->\r\n");
      out.write("\t<div class=\"pageheader-content row\">\r\n");
      out.write("            <div class=\"col-full\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"featured\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"featured__column featured__column--big\">\r\n");
      out.write("                        <div class=\"entry\" style=\"background-image:url('/template/web/images/logo/featured-guitarman.jpg')/*tpa=https://preview.colorlib.com/theme/philosophy/images/thumbs/featured/featured-guitarman.jpg*/;\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__content\">\r\n");
      out.write("                                <span class=\"entry__category\"><a href=\"#0\">Music</a></span>\r\n");
      out.write("\r\n");
      out.write("                                <h1><a href=\"#0\" title=\"\">What Your Music Preference Says About You and Your Personality.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"entry__info\">\r\n");
      out.write("                                    <a href=\"#0\" class=\"entry__profile-pic\">\r\n");
      out.write("                                        <img class=\"avatar\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" alt=\"\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <ul class=\"entry__meta\">\r\n");
      out.write("                                        <li><a href=\"#0\">John Doe</a></li>\r\n");
      out.write("                                        <li>December 29, 2017</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> <!-- end entry__content -->\r\n");
      out.write("\r\n");
      out.write("                        </div> <!-- end entry -->\r\n");
      out.write("                    </div> <!-- end featured__big -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"featured__column featured__column--small\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"entry\" style=\"background-image:url('/template/web/images/logo/featured-watch.jpg')/*tpa=https://preview.colorlib.com/theme/philosophy/images/thumbs/featured/featured-watch.jpg*/;\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__content\">\r\n");
      out.write("                                <span class=\"entry__category\"><a href=\"#0\">Management</a></span>\r\n");
      out.write("\r\n");
      out.write("                                <h1><a href=\"#0\" title=\"\">The Pomodoro Technique Really Works.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"entry__info\">\r\n");
      out.write("                                    <a href=\"#0\" class=\"entry__profile-pic\">\r\n");
      out.write("                                        <img class=\"avatar\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" tppabs=\"\" alt=\"\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <ul class=\"entry__meta\">\r\n");
      out.write("                                        <li><a href=\"#0\">John Doe</a></li>\r\n");
      out.write("                                        <li>December 27, 2017</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> <!-- end entry__content -->\r\n");
      out.write("\r\n");
      out.write("                        </div> <!-- end entry -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"entry\" style=\"background-image:url('/template/web/images/logo/featured-beetle.jpg')/*tpa=https://preview.colorlib.com/theme/philosophy/images/thumbs/featured/featured-beetle.jpg*/;\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__content\">\r\n");
      out.write("                                <span class=\"entry__category\"><a href=\"#0\">LifeStyle</a></span>\r\n");
      out.write("\r\n");
      out.write("                                <h1><a href=\"#0\" title=\"\">Throwback To The Good Old Days.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"entry__info\">\r\n");
      out.write("                                    <a href=\"#0\" class=\"entry__profile-pic\">\r\n");
      out.write("                                        <img class=\"avatar\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" tppabs=\"\" alt=\"\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <ul class=\"entry__meta\">\r\n");
      out.write("                                        <li><a href=\"#0\">John Doe</a></li>\r\n");
      out.write("                                        <li>December 21, 2017</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div> <!-- end entry__content -->\r\n");
      out.write("\r\n");
      out.write("                        </div> <!-- end entry -->\r\n");
      out.write("\r\n");
      out.write("                    </div> <!-- end featured__small -->\r\n");
      out.write("                </div> <!-- end featured -->\r\n");
      out.write("\r\n");
      out.write("            </div> <!-- end col-full -->\r\n");
      out.write("        </div> <!-- end pageheader-content row -->\r\n");
      out.write("\r\n");
      out.write("    </section> <!-- end s-pageheader -->\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"s-content\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row masonry-wrap\">\r\n");
      out.write("            <div class=\"masonry\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"grid-sizer\"></div>\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" tppabs=\"\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/lamp-400.jpg 1x, images/thumbs/masonry/lamp-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 15, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">Just a Standard Format Post.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Design</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Photography</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-quote\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <blockquote>\r\n");
      out.write("                                <p>Good design is making something intelligible and memorable. Great design is making something memorable and meaningful.</p>\r\n");
      out.write("\r\n");
      out.write("                                <cite>Dieter Rams</cite>\r\n");
      out.write("                        </blockquote>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"tulips-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/tulips-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/tulips-400.jpg 1x, images/thumbs/masonry/tulips-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 15, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">10 Interesting Facts About Caffeine.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Health</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"cookies-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/cookies-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/cookies-400.jpg 1x, images/thumbs/masonry/cookies-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">No Sugar Oatmeal Cookies.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Cooking</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Health</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"wheel-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/wheel-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/wheel-400.jpg 1x, images/thumbs/masonry/wheel-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">Visiting Theme Parks Improves Your Health.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"#\">Health</a>\r\n");
      out.write("                                <a href=\"#\">Lifestyle</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-video\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb video-image\">\r\n");
      out.write("                        <a href=\"javascript:if(confirm(%27https://player.vimeo.com/video/117310401?color=01aef0&title=0&byline=0&portrait=0  \\n\\nThis file was not retrieved by Teleport Ultra, because it is addressed on a domain or path outside the boundaries set for its Starting Address.  \\n\\nDo you want to open it from the server?%27))window.location=%27https://player.vimeo.com/video/117310401?color=01aef0&title=0&byline=0&portrait=0%27\" tppabs=\"https://player.vimeo.com/video/117310401?color=01aef0&title=0&byline=0&portrait=0\" data-lity>\r\n");
      out.write("                            <img src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-video.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-video.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-video.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-video.html\">Key Benefits Of Family Photography.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Family</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Photography</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-gallery\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb slider\">\r\n");
      out.write("                        <div class=\"slider__slides\">\r\n");
      out.write("                            <div class=\"slider__slide\">\r\n");
      out.write("                                <img src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" \r\n");
      out.write("                                        srcset=\"images/thumbs/masonry/gallery/gallery-1-400.jpg 1x, images/thumbs/masonry/gallery/gallery-1-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"slider__slide\">\r\n");
      out.write("                                <img src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" \r\n");
      out.write("                                        srcset=\"images/thumbs/masonry/gallery/gallery-2-400.jpg 1x, images/thumbs/masonry/gallery/gallery-2-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"slider__slide\">\r\n");
      out.write("                                <img src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" \r\n");
      out.write("                                        srcset=\"images/thumbs/masonry/gallery/gallery-3-400.jpg 1x, images/thumbs/masonry/gallery/gallery-3-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-gallery.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-gallery.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-gallery.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-gallery.html\">Workspace Design Trends and Ideas.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Work</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Management</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-audio\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-audio.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-audio.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"guitarman-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/guitarman-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/guitarman-400.jpg 1x, images/thumbs/masonry/guitarman-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"audio-wrap\">\r\n");
      out.write("                            <audio id=\"player\" src=\"AirReview-Landmarks-02-ChasingCorporate.mp3\" tppabs=\"https://cdn.colorlib.com/etc/philosophy/media/AirReview-Landmarks-02-ChasingCorporate.mp3\" width=\"100%\" height=\"42\" controls=\"controls\"></audio>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-audio.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-audio.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-audio.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-audio.html\">What Your Music Preference Says About You and Your Personality.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Music</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Lifestyle</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-link\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <div class=\"link-wrap\">\r\n");
      out.write("                            <p>The Only Resource You Will Need To Start a Blog Using WordPress.</p>\r\n");
      out.write("                            <cite>\r\n");
      out.write("                                <a target=\"_blank\" href=\"javascript:if(confirm(%27https://colorlib.com/  \\n\\nThis file was not retrieved by Teleport Ultra, because it is addressed on a domain or path outside the boundaries set for its Starting Address.  \\n\\nDo you want to open it from the server?%27))window.location=%27https://colorlib.com/%27\" tppabs=\"https://colorlib.com/\">https://colorlib.com</a>\r\n");
      out.write("                            </cite>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"jump-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/jump-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/jump-400.jpg 1x, images/thumbs/masonry/jump-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">Create Meaningful Family Moments.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Family</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Relationship</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"beetle-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/beetle-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/beetle-400.jpg 1x, images/thumbs/masonry/beetle-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">Throwback To The Good Old Days.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Lifestyle</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"fuji-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/fuji-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/fuji-400.jpg 1x, images/thumbs/masonry/fuji-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">Just Another  Standard Format Post.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Design</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Photography</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("                <article class=\"masonry__brick entry format-standard\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__thumb\">\r\n");
      out.write("                        <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\" class=\"entry__thumb-link\">\r\n");
      out.write("                            <img src=\"sydney-400.jpg\" tppabs=\"https://preview.colorlib.com/theme/philosophy/images/thumbs/masonry/sydney-400.jpg\"\r\n");
      out.write("                                    srcset=\"images/thumbs/masonry/sydney-400.jpg 1x, images/thumbs/masonry/sydney-800.jpg 2x\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"entry__text\">\r\n");
      out.write("                        <div class=\"entry__header\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"entry__date\">\r\n");
      out.write("                                <a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">December 10, 2017</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"entry__title\"><a href=\"single-standard.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/single-standard.html\">Planning Your First Trip to Sydney.</a></h1>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__excerpt\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"entry__meta\">\r\n");
      out.write("                            <span class=\"entry__meta-links\">\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Travel</a>\r\n");
      out.write("                                <a href=\"category.html\" tppabs=\"https://preview.colorlib.com/theme/philosophy/category.html\">Vacation</a>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </article> <!-- end article -->\r\n");
      out.write("\r\n");
      out.write("            </div> <!-- end masonry -->\r\n");
      out.write("        </div> <!-- end masonry-wrap -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-full\">\r\n");
      out.write("                <nav class=\"pgn\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a class=\"pgn__prev\" href=\"#0\">Prev</a></li>\r\n");
      out.write("                        <li><a class=\"pgn__num\" href=\"#0\">1</a></li>\r\n");
      out.write("                        <li><span class=\"pgn__num current\">2</span></li>\r\n");
      out.write("                        <li><a class=\"pgn__num\" href=\"#0\">3</a></li>\r\n");
      out.write("                        <li><a class=\"pgn__num\" href=\"#0\">4</a></li>\r\n");
      out.write("                        <li><a class=\"pgn__num\" href=\"#0\">5</a></li>\r\n");
      out.write("                        <li><span class=\"pgn__num dots\">…</span></li>\r\n");
      out.write("                        <li><a class=\"pgn__num\" href=\"#0\">8</a></li>\r\n");
      out.write("                        <li><a class=\"pgn__next\" href=\"#0\">Next</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section> <!-- s-content -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_dec_005ftitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:title
    com.opensymphony.module.sitemesh.taglib.decorator.TitleTag _jspx_th_dec_005ftitle_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.TitleTag) _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.TitleTag.class);
    boolean _jspx_th_dec_005ftitle_005f0_reused = false;
    try {
      _jspx_th_dec_005ftitle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_dec_005ftitle_005f0.setParent(null);
      // /views/web/home.jsp(8,7) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_dec_005ftitle_005f0.setDefault("Trang Chủ");
      int _jspx_eval_dec_005ftitle_005f0 = _jspx_th_dec_005ftitle_005f0.doStartTag();
      if (_jspx_th_dec_005ftitle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.reuse(_jspx_th_dec_005ftitle_005f0);
      _jspx_th_dec_005ftitle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_dec_005ftitle_005f0, _jsp_getInstanceManager(), _jspx_th_dec_005ftitle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/web/home.jsp(27,65) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/template/web/images/logo/user-03.jpg");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/web/home.jsp(51,65) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/template/web/images/logo/user-03.jpg");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/web/home.jsp(72,65) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/template/web/images/logo/user-03.jpg");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/web/home.jsp(103,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/template/web/images/logo/lamp-400.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/web/home.jsp(246,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/template/web/images/logo/shutterbug-400.jpg");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/web/home.jsp(280,42) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/template/web/images/logo/gallery-1-400.jpg");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/web/home.jsp(284,42) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/template/web/images/logo/gallery-2-400.jpg");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/web/home.jsp(288,42) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/template/web/images/logo/gallery-3-400.jpg");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }
}
